### ISSUE TITLE
Add cargo fmt check to travis CI

### ISSUE THREAD

**Issue by andygrove** [andygrove/ballista#25]
We want to use `cargo fmt` to keep the code formatted consistently. The usual approach to this is to have the build fail if the code isn't formatted correctly.

Here is some example travis yaml I found that should be pretty close to what we need:

```yaml
language: rust
before_script:
  - rustup toolchain install nightly
  - rustup component add --toolchain nightly rustfmt-preview
  - which rustfmt || cargo install --force rustfmt-nightly
script:
  - cargo +nightly fmt --all -- --write-mode=diff
  - cargo build
  - cargo test
```
